In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
              [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [9]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
# Creat a DataFrame from a Numpy arrray
import pandas as pd

df = pd.DataFrame(a2)

In [21]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating arrays

In [22]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int64')

In [27]:
ones = np.ones((10,3), int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
ones.dtype

dtype('int64')

In [29]:
type(ones)

numpy.ndarray

In [30]:
zeros = np.zeros((2,3))

In [31]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
zeros.dtype

dtype('float64')

In [36]:
range_array = np.arange(3,10,3)

In [37]:
range_array

array([3, 6, 9])

In [39]:
random_array = np.random.randint(0,10,(3,5))

In [40]:
random_array

array([[2, 3, 2, 0, 7],
       [5, 7, 0, 0, 0],
       [5, 6, 6, 2, 0]])

In [41]:
random_array.size

15

In [42]:
random_array.shape

(3, 5)

In [44]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.58218707, 0.72739889, 0.18201853],
       [0.92286257, 0.36004276, 0.33968184],
       [0.91984219, 0.37034427, 0.69485411],
       [0.94669711, 0.74655146, 0.61409055],
       [0.50799121, 0.15416288, 0.72746432]])

In [45]:
random_array2.shape

(5, 3)

In [46]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.04122048, 0.54872612, 0.46138425],
       [0.980927  , 0.12861071, 0.753872  ],
       [0.96384451, 0.91033115, 0.34714273],
       [0.83425856, 0.43325801, 0.43433517],
       [0.57517844, 0.26975022, 0.32910233]])

In [61]:
# Pseudo-random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrices

In [62]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a1

array([1, 2, 3])

In [64]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [65]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [66]:
a1[0]

1

In [67]:
a2[0]

array([1., 2., 3.])

In [68]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
a2[1]

array([4. , 5. , 6.5])

In [71]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [72]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [73]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [75]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,:1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])

## 4. Manipulating & comaring arrays

 ### Arithmatic

In [77]:
a1

array([1, 2, 3])

In [78]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [79]:
a1 + ones

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [80]:
a1 - ones

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [81]:
a1 * ones

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [83]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [82]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [84]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [87]:
a2 

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [88]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [89]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [90]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [92]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [91]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [93]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [95]:
a1

array([1, 2, 3])

In [94]:
a1 % 2

array([1, 0, 1])

In [96]:
a2 % 2

array([[1. , 0. , 1. ],
       [0. , 1. , 0.5]])

In [97]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [98]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])